# Generated by Django 5.2.17 on 2026-09-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "userid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("access_role", models.CharField(max_length=100)),
                ("professional_role", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(db_index=True, default="Active", max_length=50),
                ),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("profile_photo", models.URLField(blank=True)),
                ("internal_notes", models.CharField(blank=True, max_length=500)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_banner", models.URLField(blank=True)),
            ],
            options={
                "db_table": "users",
                "ordering": ["full_name"],
            },
        ),
    ]
