# Generated by Django 5.2.17 on 2026-09-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_seed_document_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle",
            name="author",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="category",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="NewsArticle",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="ResourceCategory",
        ),
    ]
