# Generated by Django 5.2.17 on 2026-09-28 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_agent_relationships(apps, schema_editor):
    Agent = apps.get_model("content", "Agent")
    Agency = apps.get_model("content", "Agency")

    for agent in Agent.objects.all():
        if agent.company:
            agency, _ = Agency.objects.get_or_create(company_name=agent.company)
            agent.agency = agency
        agent.userid_uuid = uuid.uuid5(uuid.NAMESPACE_URL, f"atlas-agent:{agent.userid}")
        agent.save(update_fields=("agency", "userid_uuid"))


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_remove_newsarticle_author_remove_resource_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "agency_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_logo",
                    models.ImageField(blank=True, upload_to="agencies/logos/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("company_phone", models.CharField(blank=True, max_length=50)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Agencies",
                "ordering": ["company_name"],
                "db_table": "agencies",
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="content.agency",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="userid_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_agent_relationships, migrations.RunPython.noop),
        migrations.RemoveField(model_name="agent", name="access_role"),
        migrations.RemoveField(model_name="agent", name="company"),
        migrations.RemoveField(model_name="agent", name="company_banner"),
        migrations.RemoveField(model_name="agent", name="professional_role"),
        migrations.AlterField(
            model_name="agent",
            name="profile_photo",
            field=models.ImageField(blank=True, upload_to="agents/profiles/"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                db_index=True,
                default="Active",
                max_length=8,
            ),
        ),
        migrations.RemoveField(model_name="agent", name="userid"),
        migrations.RenameField(
            model_name="agent",
            old_name="userid_uuid",
            new_name="userid",
        ),
        migrations.AlterField(
            model_name="agent",
            name="userid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
