# Generated by Django 5.2.17 on 2026-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0007_agency_remove_agent_access_role_remove_agent_company_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="company_banner",
            field=models.ImageField(blank=True, upload_to="agencies/banners/"),
        ),
    ]
