# Generated by Django 5.2.17 on 2026-09-29 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_documentfolder_document_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="updated_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The source file's last-modified date when supplied by the uploader.",
            ),
        ),
    ]
